---
    
- name: Process Required CSV
  block:  
          
    - name: Reading OSPF CSV file
      read_csv:
        path: "roles/Layer3/CSV/OSPF.csv"
        delimiter: ","
      register: ospf

    - name: Reading BGP CSV file
      read_csv:
        path: "roles/Layer3/CSV/BGP.csv"
        delimiter: ","
      register: bgp
      
- name: Implementing Required Configs
  block:
  
    - name: Setting appropriate hostname
      ios_config:
        lines: hostname {{inventory_hostname }}    
       
    - name: int config
      ios_config: src=roles/Layer3/template/int_config.j2 
      with_items: "{{ layer3_interfaces }}"
      when: "item.device in inventory_hostname"
   
    - name: ospf config
      ios_config: src=roles/Layer3/template/ospf.j2 
      tags: ospf_config        
      with_items: "{{ layer3_interfaces }}"
      when: "item.device in inventory_hostname"
    
    - name: bgp config
      ios_config: src=roles/Layer3/template/bgp.j2
      tags: bgp_config   
      



      
      
