---

- name: Process Required CSV
  block:    
    - name: Reading Vlan CSV file
      read_csv:
        path: "roles/Layer2/CSV/sl2.csv"
        delimiter: ","
      register: vlans
      
    - name: Reading Unused Ports CSV file
      read_csv:
        path: "roles/Layer2/CSV/Unused_Ports.csv"
        delimiter: ","
      register: unused_ports
      
    - name: Reading Trunk CSV file
      read_csv:
        path: "roles/Layer2/CSV/trunk_ports.csv"
        delimiter: ","
      register: trunk_port

    - name: Reading Access CSV file
      read_csv:
        path: "roles/Layer2/CSV/access_ports.csv"
        delimiter: ","
      register: access_port     
       
    - name: Reading Etherchannel CSV file
      read_csv:
        path: "roles/Layer2/CSV/etherchannel_ports.csv"
        delimiter: ","
      register: etherchannel
    
    - name: Reading Spanning Tree CSV file
      read_csv:
        path: "roles/Layer2/CSV/spanning_tree.csv"
        delimiter: ","
      register: spanning_tree
    
    - name: Reading HSRP CSV file
      read_csv:
        path: "roles/Layer2/CSV/HSRP.csv"
        delimiter: ","
      register: hsrp

- name: Implementing Required Configs
  block:
    - name: Setting appropriate hostname
      ios_config:
        lines: hostname {{inventory_hostname }}
    
    - name: vlan config
      ios_config: src=roles/Layer2/template/vlan.j2
      tags: vlan_config
    
    - name: shutting down unused ports and assigning them to vlan 70
      ios_config: src=roles/Layer2/template/Unused_Ports.j2
      tags: unused_ports_config
    
    - name: trunk port config
      ios_config: src=roles/Layer2/template/trunk_ports.j2 
      tags: trunk_config
      vars:
        ansible_command_timeout: 120

    - name: access port config
      ios_config: src=roles/Layer2/template/access_ports.j2 
      tags: access_config
      vars:
        ansible_command_timeout: 120
      
    - name: etherchannel config
      ios_config: src=roles/Layer2/template/etherchannel.j2
      tags: etherchannel_config  
      vars:
        ansible_command_timeout: 120
        
    - name: hsrp config
      ios_config: src=roles/Layer2/template/hsrp.j2
      tags: hsrp_config
      vars:
        ansible_command_timeout: 120
   
    - name: stp config
      ios_config: src=roles/Layer2/template/spanning_tree_info.j2 
      tags: stp_config
      vars:
        ansible_command_timeout: 240


