---
- setup:
    gather_subset:
      - 'min'  
       
- name: Display the current timestamp
  set_fact:
    time: "{{ ansible_date_time.date }}-{{ansible_date_time.time}}-{{inventory_hostname}}"

- name: "Backup Cisco Config"
  ios_command:
    commands:
     - command: copy run tftp://{{ item }}/{{ time }}
       prompt: 
       - 'Address or name of remote host?'
       - 'Destination filename ?'
       answer: 
       - "\r"
       - "\r"
  with_items: "{{ tftp_server }}"
